// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: oss.proto

package oss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedHeader) Reset() {
	*x = SignedHeader{}
	mi := &file_oss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedHeader) ProtoMessage() {}

func (x *SignedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedHeader.ProtoReflect.Descriptor instead.
func (*SignedHeader) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{0}
}

func (x *SignedHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SignedHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PresignGeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUrl     string                 `protobuf:"bytes,1,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	SignedMethod  string                 `protobuf:"bytes,2,opt,name=signed_method,json=signedMethod,proto3" json:"signed_method,omitempty"`
	Expiration    string                 `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	SignedHeaders []*SignedHeader        `protobuf:"bytes,4,rep,name=signed_headers,json=signedHeaders,proto3" json:"signed_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignGeneralResponse) Reset() {
	*x = PresignGeneralResponse{}
	mi := &file_oss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignGeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignGeneralResponse) ProtoMessage() {}

func (x *PresignGeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignGeneralResponse.ProtoReflect.Descriptor instead.
func (*PresignGeneralResponse) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{1}
}

func (x *PresignGeneralResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *PresignGeneralResponse) GetSignedMethod() string {
	if x != nil {
		return x.SignedMethod
	}
	return ""
}

func (x *PresignGeneralResponse) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *PresignGeneralResponse) GetSignedHeaders() []*SignedHeader {
	if x != nil {
		return x.SignedHeaders
	}
	return nil
}

type PresignPutObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignPutObjectRequest) Reset() {
	*x = PresignPutObjectRequest{}
	mi := &file_oss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignPutObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignPutObjectRequest) ProtoMessage() {}

func (x *PresignPutObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignPutObjectRequest.ProtoReflect.Descriptor instead.
func (*PresignPutObjectRequest) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{2}
}

func (x *PresignPutObjectRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignPutObjectRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PresignPutObjectRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *PresignPutObjectRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type PresignPutObjectResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	PresignResponse *PresignGeneralResponse `protobuf:"bytes,1,opt,name=presign_response,json=presignResponse,proto3" json:"presign_response,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresignPutObjectResponse) Reset() {
	*x = PresignPutObjectResponse{}
	mi := &file_oss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignPutObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignPutObjectResponse) ProtoMessage() {}

func (x *PresignPutObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignPutObjectResponse.ProtoReflect.Descriptor instead.
func (*PresignPutObjectResponse) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{3}
}

func (x *PresignPutObjectResponse) GetPresignResponse() *PresignGeneralResponse {
	if x != nil {
		return x.PresignResponse
	}
	return nil
}

type PresignGetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketPrefix  string                 `protobuf:"bytes,1,opt,name=bucket_prefix,json=bucketPrefix,proto3" json:"bucket_prefix,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Getter        string                 `protobuf:"bytes,3,opt,name=getter,proto3" json:"getter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignGetObjectRequest) Reset() {
	*x = PresignGetObjectRequest{}
	mi := &file_oss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignGetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignGetObjectRequest) ProtoMessage() {}

func (x *PresignGetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignGetObjectRequest.ProtoReflect.Descriptor instead.
func (*PresignGetObjectRequest) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{4}
}

func (x *PresignGetObjectRequest) GetBucketPrefix() string {
	if x != nil {
		return x.BucketPrefix
	}
	return ""
}

func (x *PresignGetObjectRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignGetObjectRequest) GetGetter() string {
	if x != nil {
		return x.Getter
	}
	return ""
}

type PresignGetObjectResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	PresignResponse *PresignGeneralResponse `protobuf:"bytes,1,opt,name=presign_response,json=presignResponse,proto3" json:"presign_response,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresignGetObjectResponse) Reset() {
	*x = PresignGetObjectResponse{}
	mi := &file_oss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignGetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignGetObjectResponse) ProtoMessage() {}

func (x *PresignGetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignGetObjectResponse.ProtoReflect.Descriptor instead.
func (*PresignGetObjectResponse) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{5}
}

func (x *PresignGetObjectResponse) GetPresignResponse() *PresignGeneralResponse {
	if x != nil {
		return x.PresignResponse
	}
	return nil
}

type ObjectOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectOwner) Reset() {
	*x = ObjectOwner{}
	mi := &file_oss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectOwner) ProtoMessage() {}

func (x *ObjectOwner) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectOwner.ProtoReflect.Descriptor instead.
func (*ObjectOwner) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectOwner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectOwner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ObjectProperties struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size           int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Etag           string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified   string                 `protobuf:"bytes,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	StorageClass   string                 `protobuf:"bytes,6,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	Owner          *ObjectOwner           `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	RestoreInfo    string                 `protobuf:"bytes,8,opt,name=restore_info,json=restoreInfo,proto3" json:"restore_info,omitempty"`
	TransitionTime string                 `protobuf:"bytes,9,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObjectProperties) Reset() {
	*x = ObjectProperties{}
	mi := &file_oss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectProperties) ProtoMessage() {}

func (x *ObjectProperties) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectProperties.ProtoReflect.Descriptor instead.
func (*ObjectProperties) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectProperties) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectProperties) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectProperties) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectProperties) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectProperties) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *ObjectProperties) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *ObjectProperties) GetOwner() *ObjectOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ObjectProperties) GetRestoreInfo() string {
	if x != nil {
		return x.RestoreInfo
	}
	return ""
}

func (x *ObjectProperties) GetTransitionTime() string {
	if x != nil {
		return x.TransitionTime
	}
	return ""
}

type CommonPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonPrefix) Reset() {
	*x = CommonPrefix{}
	mi := &file_oss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonPrefix) ProtoMessage() {}

func (x *CommonPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonPrefix.ProtoReflect.Descriptor instead.
func (*CommonPrefix) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{8}
}

func (x *CommonPrefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketPrefix  string                 `protobuf:"bytes,1,opt,name=bucket_prefix,json=bucketPrefix,proto3" json:"bucket_prefix,omitempty"`
	Marker        string                 `protobuf:"bytes,2,opt,name=marker,proto3" json:"marker,omitempty"`
	MaxKeys       int32                  `protobuf:"varint,3,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	Getter        string                 `protobuf:"bytes,4,opt,name=getter,proto3" json:"getter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_oss_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{9}
}

func (x *ListObjectsRequest) GetBucketPrefix() string {
	if x != nil {
		return x.BucketPrefix
	}
	return ""
}

func (x *ListObjectsRequest) GetMarker() string {
	if x != nil {
		return x.Marker
	}
	return ""
}

func (x *ListObjectsRequest) GetMaxKeys() int32 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

func (x *ListObjectsRequest) GetGetter() string {
	if x != nil {
		return x.Getter
	}
	return ""
}

type ListObjectsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix         string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Marker         string                 `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
	MaxKeys        int32                  `protobuf:"varint,4,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	Delimiter      string                 `protobuf:"bytes,5,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	IsTruncated    bool                   `protobuf:"varint,6,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	NextMarker     string                 `protobuf:"bytes,7,opt,name=next_marker,json=nextMarker,proto3" json:"next_marker,omitempty"`
	EncodingType   string                 `protobuf:"bytes,8,opt,name=encoding_type,json=encodingType,proto3" json:"encoding_type,omitempty"`
	Contents       []*ObjectProperties    `protobuf:"bytes,9,rep,name=contents,proto3" json:"contents,omitempty"`
	CommonPrefixes []*CommonPrefix        `protobuf:"bytes,10,rep,name=common_prefixes,json=commonPrefixes,proto3" json:"common_prefixes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_oss_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oss_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_oss_proto_rawDescGZIP(), []int{10}
}

func (x *ListObjectsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListObjectsResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListObjectsResponse) GetMarker() string {
	if x != nil {
		return x.Marker
	}
	return ""
}

func (x *ListObjectsResponse) GetMaxKeys() int32 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

func (x *ListObjectsResponse) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

func (x *ListObjectsResponse) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

func (x *ListObjectsResponse) GetNextMarker() string {
	if x != nil {
		return x.NextMarker
	}
	return ""
}

func (x *ListObjectsResponse) GetEncodingType() string {
	if x != nil {
		return x.EncodingType
	}
	return ""
}

func (x *ListObjectsResponse) GetContents() []*ObjectProperties {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ListObjectsResponse) GetCommonPrefixes() []*CommonPrefix {
	if x != nil {
		return x.CommonPrefixes
	}
	return nil
}

var File_oss_proto protoreflect.FileDescriptor

const file_oss_proto_rawDesc = "" +
	"\n" +
	"\toss.proto\x12\x03oss\"6\n" +
	"\fSignedHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb6\x01\n" +
	"\x16PresignGeneralResponse\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x01 \x01(\tR\tsignedUrl\x12#\n" +
	"\rsigned_method\x18\x02 \x01(\tR\fsignedMethod\x12\x1e\n" +
	"\n" +
	"expiration\x18\x03 \x01(\tR\n" +
	"expiration\x128\n" +
	"\x0esigned_headers\x18\x04 \x03(\v2\x11.oss.SignedHeaderR\rsignedHeaders\"x\n" +
	"\x17PresignPutObjectRequest\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\"b\n" +
	"\x18PresignPutObjectResponse\x12F\n" +
	"\x10presign_response\x18\x01 \x01(\v2\x1b.oss.PresignGeneralResponseR\x0fpresignResponse\"u\n" +
	"\x17PresignGetObjectRequest\x12#\n" +
	"\rbucket_prefix\x18\x01 \x01(\tR\fbucketPrefix\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06getter\x18\x03 \x01(\tR\x06getter\"b\n" +
	"\x18PresignGetObjectResponse\x12F\n" +
	"\x10presign_response\x18\x01 \x01(\v2\x1b.oss.PresignGeneralResponseR\x0fpresignResponse\"@\n" +
	"\vObjectOwner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\x9e\x02\n" +
	"\x10ObjectProperties\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12#\n" +
	"\rlast_modified\x18\x05 \x01(\tR\flastModified\x12#\n" +
	"\rstorage_class\x18\x06 \x01(\tR\fstorageClass\x12&\n" +
	"\x05owner\x18\a \x01(\v2\x10.oss.ObjectOwnerR\x05owner\x12!\n" +
	"\frestore_info\x18\b \x01(\tR\vrestoreInfo\x12'\n" +
	"\x0ftransition_time\x18\t \x01(\tR\x0etransitionTime\"&\n" +
	"\fCommonPrefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\x84\x01\n" +
	"\x12ListObjectsRequest\x12#\n" +
	"\rbucket_prefix\x18\x01 \x01(\tR\fbucketPrefix\x12\x16\n" +
	"\x06marker\x18\x02 \x01(\tR\x06marker\x12\x19\n" +
	"\bmax_keys\x18\x03 \x01(\x05R\amaxKeys\x12\x16\n" +
	"\x06getter\x18\x04 \x01(\tR\x06getter\"\xea\x02\n" +
	"\x13ListObjectsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06marker\x18\x03 \x01(\tR\x06marker\x12\x19\n" +
	"\bmax_keys\x18\x04 \x01(\x05R\amaxKeys\x12\x1c\n" +
	"\tdelimiter\x18\x05 \x01(\tR\tdelimiter\x12!\n" +
	"\fis_truncated\x18\x06 \x01(\bR\visTruncated\x12\x1f\n" +
	"\vnext_marker\x18\a \x01(\tR\n" +
	"nextMarker\x12#\n" +
	"\rencoding_type\x18\b \x01(\tR\fencodingType\x121\n" +
	"\bcontents\x18\t \x03(\v2\x15.oss.ObjectPropertiesR\bcontents\x12:\n" +
	"\x0fcommon_prefixes\x18\n" +
	" \x03(\v2\x11.oss.CommonPrefixR\x0ecommonPrefixes2\xf6\x01\n" +
	"\x10AliyunOssService\x12O\n" +
	"\x10PresignPutObject\x12\x1c.oss.PresignPutObjectRequest\x1a\x1d.oss.PresignPutObjectResponse\x12O\n" +
	"\x10PresignGetObject\x12\x1c.oss.PresignGetObjectRequest\x1a\x1d.oss.PresignGetObjectResponse\x12@\n" +
	"\vListObjects\x12\x17.oss.ListObjectsRequest\x1a\x18.oss.ListObjectsResponseB%Z#example.com/nano_template/proto/ossb\x06proto3"

var (
	file_oss_proto_rawDescOnce sync.Once
	file_oss_proto_rawDescData []byte
)

func file_oss_proto_rawDescGZIP() []byte {
	file_oss_proto_rawDescOnce.Do(func() {
		file_oss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oss_proto_rawDesc), len(file_oss_proto_rawDesc)))
	})
	return file_oss_proto_rawDescData
}

var file_oss_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oss_proto_goTypes = []any{
	(*SignedHeader)(nil),             // 0: oss.SignedHeader
	(*PresignGeneralResponse)(nil),   // 1: oss.PresignGeneralResponse
	(*PresignPutObjectRequest)(nil),  // 2: oss.PresignPutObjectRequest
	(*PresignPutObjectResponse)(nil), // 3: oss.PresignPutObjectResponse
	(*PresignGetObjectRequest)(nil),  // 4: oss.PresignGetObjectRequest
	(*PresignGetObjectResponse)(nil), // 5: oss.PresignGetObjectResponse
	(*ObjectOwner)(nil),              // 6: oss.ObjectOwner
	(*ObjectProperties)(nil),         // 7: oss.ObjectProperties
	(*CommonPrefix)(nil),             // 8: oss.CommonPrefix
	(*ListObjectsRequest)(nil),       // 9: oss.ListObjectsRequest
	(*ListObjectsResponse)(nil),      // 10: oss.ListObjectsResponse
}
var file_oss_proto_depIdxs = []int32{
	0,  // 0: oss.PresignGeneralResponse.signed_headers:type_name -> oss.SignedHeader
	1,  // 1: oss.PresignPutObjectResponse.presign_response:type_name -> oss.PresignGeneralResponse
	1,  // 2: oss.PresignGetObjectResponse.presign_response:type_name -> oss.PresignGeneralResponse
	6,  // 3: oss.ObjectProperties.owner:type_name -> oss.ObjectOwner
	7,  // 4: oss.ListObjectsResponse.contents:type_name -> oss.ObjectProperties
	8,  // 5: oss.ListObjectsResponse.common_prefixes:type_name -> oss.CommonPrefix
	2,  // 6: oss.AliyunOssService.PresignPutObject:input_type -> oss.PresignPutObjectRequest
	4,  // 7: oss.AliyunOssService.PresignGetObject:input_type -> oss.PresignGetObjectRequest
	9,  // 8: oss.AliyunOssService.ListObjects:input_type -> oss.ListObjectsRequest
	3,  // 9: oss.AliyunOssService.PresignPutObject:output_type -> oss.PresignPutObjectResponse
	5,  // 10: oss.AliyunOssService.PresignGetObject:output_type -> oss.PresignGetObjectResponse
	10, // 11: oss.AliyunOssService.ListObjects:output_type -> oss.ListObjectsResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_oss_proto_init() }
func file_oss_proto_init() {
	if File_oss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oss_proto_rawDesc), len(file_oss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oss_proto_goTypes,
		DependencyIndexes: file_oss_proto_depIdxs,
		MessageInfos:      file_oss_proto_msgTypes,
	}.Build()
	File_oss_proto = out.File
	file_oss_proto_goTypes = nil
	file_oss_proto_depIdxs = nil
}
