// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: oss.proto

package oss

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AliyunOssService_PresignPutObject_FullMethodName = "/oss.AliyunOssService/PresignPutObject"
	AliyunOssService_PresignGetObject_FullMethodName = "/oss.AliyunOssService/PresignGetObject"
	AliyunOssService_ListObjects_FullMethodName      = "/oss.AliyunOssService/ListObjects"
)

// AliyunOssServiceClient is the client API for AliyunOssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AliyunOssServiceClient interface {
	PresignPutObject(ctx context.Context, in *PresignPutObjectRequest, opts ...grpc.CallOption) (*PresignPutObjectResponse, error)
	PresignGetObject(ctx context.Context, in *PresignGetObjectRequest, opts ...grpc.CallOption) (*PresignGetObjectResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
}

type aliyunOssServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAliyunOssServiceClient(cc grpc.ClientConnInterface) AliyunOssServiceClient {
	return &aliyunOssServiceClient{cc}
}

func (c *aliyunOssServiceClient) PresignPutObject(ctx context.Context, in *PresignPutObjectRequest, opts ...grpc.CallOption) (*PresignPutObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignPutObjectResponse)
	err := c.cc.Invoke(ctx, AliyunOssService_PresignPutObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliyunOssServiceClient) PresignGetObject(ctx context.Context, in *PresignGetObjectRequest, opts ...grpc.CallOption) (*PresignGetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignGetObjectResponse)
	err := c.cc.Invoke(ctx, AliyunOssService_PresignGetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliyunOssServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, AliyunOssService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliyunOssServiceServer is the server API for AliyunOssService service.
// All implementations must embed UnimplementedAliyunOssServiceServer
// for forward compatibility.
type AliyunOssServiceServer interface {
	PresignPutObject(context.Context, *PresignPutObjectRequest) (*PresignPutObjectResponse, error)
	PresignGetObject(context.Context, *PresignGetObjectRequest) (*PresignGetObjectResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	mustEmbedUnimplementedAliyunOssServiceServer()
}

// UnimplementedAliyunOssServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAliyunOssServiceServer struct{}

func (UnimplementedAliyunOssServiceServer) PresignPutObject(context.Context, *PresignPutObjectRequest) (*PresignPutObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PresignPutObject not implemented")
}
func (UnimplementedAliyunOssServiceServer) PresignGetObject(context.Context, *PresignGetObjectRequest) (*PresignGetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PresignGetObject not implemented")
}
func (UnimplementedAliyunOssServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedAliyunOssServiceServer) mustEmbedUnimplementedAliyunOssServiceServer() {}
func (UnimplementedAliyunOssServiceServer) testEmbeddedByValue()                          {}

// UnsafeAliyunOssServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AliyunOssServiceServer will
// result in compilation errors.
type UnsafeAliyunOssServiceServer interface {
	mustEmbedUnimplementedAliyunOssServiceServer()
}

func RegisterAliyunOssServiceServer(s grpc.ServiceRegistrar, srv AliyunOssServiceServer) {
	// If the following call panics, it indicates UnimplementedAliyunOssServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AliyunOssService_ServiceDesc, srv)
}

func _AliyunOssService_PresignPutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignPutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliyunOssServiceServer).PresignPutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliyunOssService_PresignPutObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliyunOssServiceServer).PresignPutObject(ctx, req.(*PresignPutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliyunOssService_PresignGetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignGetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliyunOssServiceServer).PresignGetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliyunOssService_PresignGetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliyunOssServiceServer).PresignGetObject(ctx, req.(*PresignGetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliyunOssService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliyunOssServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliyunOssService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliyunOssServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AliyunOssService_ServiceDesc is the grpc.ServiceDesc for AliyunOssService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AliyunOssService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oss.AliyunOssService",
	HandlerType: (*AliyunOssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PresignPutObject",
			Handler:    _AliyunOssService_PresignPutObject_Handler,
		},
		{
			MethodName: "PresignGetObject",
			Handler:    _AliyunOssService_PresignGetObject_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _AliyunOssService_ListObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oss.proto",
}
