// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiChatService_CreateSession_FullMethodName   = "/chat.AiChatService/CreateSession"
	AiChatService_UpdateSession_FullMethodName   = "/chat.AiChatService/UpdateSession"
	AiChatService_GetSession_FullMethodName      = "/chat.AiChatService/GetSession"
	AiChatService_ListSessions_FullMethodName    = "/chat.AiChatService/ListSessions"
	AiChatService_DeleteSession_FullMethodName   = "/chat.AiChatService/DeleteSession"
	AiChatService_Generate_FullMethodName        = "/chat.AiChatService/Generate"
	AiChatService_GenerateModal_FullMethodName   = "/chat.AiChatService/GenerateModal"
	AiChatService_Record_FullMethodName          = "/chat.AiChatService/Record"
	AiChatService_UpdateRecord_FullMethodName    = "/chat.AiChatService/UpdateRecord"
	AiChatService_ListRecords_FullMethodName     = "/chat.AiChatService/ListRecords"
	AiChatService_DeleteRecord_FullMethodName    = "/chat.AiChatService/DeleteRecord"
	AiChatService_UploadAppendixs_FullMethodName = "/chat.AiChatService/UploadAppendixs"
	AiChatService_UpdateAppendix_FullMethodName  = "/chat.AiChatService/UpdateAppendix"
	AiChatService_ListAppendixs_FullMethodName   = "/chat.AiChatService/ListAppendixs"
	AiChatService_DeleteAppendix_FullMethodName  = "/chat.AiChatService/DeleteAppendix"
)

// AiChatServiceClient is the client API for AiChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiChatServiceClient interface {
	// ai session
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessnoResponse, error)
	// ai chat
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
	GenerateModal(ctx context.Context, in *GenerateModalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateModalResponse], error)
	// ai messages
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
	// chat appendixs
	UploadAppendixs(ctx context.Context, in *UploadAppendixRequest, opts ...grpc.CallOption) (*UploadAppendixResponse, error)
	UpdateAppendix(ctx context.Context, in *UpdateAppendixRequest, opts ...grpc.CallOption) (*UpdateAppendixResponse, error)
	ListAppendixs(ctx context.Context, in *ListAppendixsRequest, opts ...grpc.CallOption) (*ListAppendixsResponse, error)
	DeleteAppendix(ctx context.Context, in *DeleteAppendixRequest, opts ...grpc.CallOption) (*DeleteAppendixResponse, error)
}

type aiChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiChatServiceClient(cc grpc.ClientConnInterface) AiChatServiceClient {
	return &aiChatServiceClient{cc}
}

func (c *aiChatServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, AiChatService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, AiChatService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, AiChatService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AiChatService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessnoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessnoResponse)
	err := c.cc.Invoke(ctx, AiChatService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiChatService_ServiceDesc.Streams[0], AiChatService_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

func (c *aiChatServiceClient) GenerateModal(ctx context.Context, in *GenerateModalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateModalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiChatService_ServiceDesc.Streams[1], AiChatService_GenerateModal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateModalRequest, GenerateModalResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_GenerateModalClient = grpc.ServerStreamingClient[GenerateModalResponse]

func (c *aiChatServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, AiChatService_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRecordResponse)
	err := c.cc.Invoke(ctx, AiChatService_UpdateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResponse)
	err := c.cc.Invoke(ctx, AiChatService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, AiChatService_DeleteRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) UploadAppendixs(ctx context.Context, in *UploadAppendixRequest, opts ...grpc.CallOption) (*UploadAppendixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAppendixResponse)
	err := c.cc.Invoke(ctx, AiChatService_UploadAppendixs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) UpdateAppendix(ctx context.Context, in *UpdateAppendixRequest, opts ...grpc.CallOption) (*UpdateAppendixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAppendixResponse)
	err := c.cc.Invoke(ctx, AiChatService_UpdateAppendix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) ListAppendixs(ctx context.Context, in *ListAppendixsRequest, opts ...grpc.CallOption) (*ListAppendixsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppendixsResponse)
	err := c.cc.Invoke(ctx, AiChatService_ListAppendixs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) DeleteAppendix(ctx context.Context, in *DeleteAppendixRequest, opts ...grpc.CallOption) (*DeleteAppendixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppendixResponse)
	err := c.cc.Invoke(ctx, AiChatService_DeleteAppendix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiChatServiceServer is the server API for AiChatService service.
// All implementations must embed UnimplementedAiChatServiceServer
// for forward compatibility.
type AiChatServiceServer interface {
	// ai session
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessnoResponse, error)
	// ai chat
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	GenerateModal(*GenerateModalRequest, grpc.ServerStreamingServer[GenerateModalResponse]) error
	// ai messages
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error)
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	// chat appendixs
	UploadAppendixs(context.Context, *UploadAppendixRequest) (*UploadAppendixResponse, error)
	UpdateAppendix(context.Context, *UpdateAppendixRequest) (*UpdateAppendixResponse, error)
	ListAppendixs(context.Context, *ListAppendixsRequest) (*ListAppendixsResponse, error)
	DeleteAppendix(context.Context, *DeleteAppendixRequest) (*DeleteAppendixResponse, error)
	mustEmbedUnimplementedAiChatServiceServer()
}

// UnimplementedAiChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiChatServiceServer struct{}

func (UnimplementedAiChatServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAiChatServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedAiChatServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAiChatServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAiChatServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessnoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedAiChatServiceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAiChatServiceServer) GenerateModal(*GenerateModalRequest, grpc.ServerStreamingServer[GenerateModalResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateModal not implemented")
}
func (UnimplementedAiChatServiceServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedAiChatServiceServer) UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (UnimplementedAiChatServiceServer) ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedAiChatServiceServer) DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedAiChatServiceServer) UploadAppendixs(context.Context, *UploadAppendixRequest) (*UploadAppendixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAppendixs not implemented")
}
func (UnimplementedAiChatServiceServer) UpdateAppendix(context.Context, *UpdateAppendixRequest) (*UpdateAppendixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAppendix not implemented")
}
func (UnimplementedAiChatServiceServer) ListAppendixs(context.Context, *ListAppendixsRequest) (*ListAppendixsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppendixs not implemented")
}
func (UnimplementedAiChatServiceServer) DeleteAppendix(context.Context, *DeleteAppendixRequest) (*DeleteAppendixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAppendix not implemented")
}
func (UnimplementedAiChatServiceServer) mustEmbedUnimplementedAiChatServiceServer() {}
func (UnimplementedAiChatServiceServer) testEmbeddedByValue()                       {}

// UnsafeAiChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiChatServiceServer will
// result in compilation errors.
type UnsafeAiChatServiceServer interface {
	mustEmbedUnimplementedAiChatServiceServer()
}

func RegisterAiChatServiceServer(s grpc.ServiceRegistrar, srv AiChatServiceServer) {
	// If the following call panics, it indicates UnimplementedAiChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiChatService_ServiceDesc, srv)
}

func _AiChatService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiChatServiceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

func _AiChatService_GenerateModal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateModalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiChatServiceServer).GenerateModal(m, &grpc.GenericServerStream[GenerateModalRequest, GenerateModalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_GenerateModalServer = grpc.ServerStreamingServer[GenerateModalResponse]

func _AiChatService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_UpdateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_DeleteRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_UploadAppendixs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAppendixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).UploadAppendixs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_UploadAppendixs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).UploadAppendixs(ctx, req.(*UploadAppendixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_UpdateAppendix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppendixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).UpdateAppendix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_UpdateAppendix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).UpdateAppendix(ctx, req.(*UpdateAppendixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_ListAppendixs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppendixsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).ListAppendixs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_ListAppendixs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).ListAppendixs(ctx, req.(*ListAppendixsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_DeleteAppendix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppendixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).DeleteAppendix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_DeleteAppendix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).DeleteAppendix(ctx, req.(*DeleteAppendixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiChatService_ServiceDesc is the grpc.ServiceDesc for AiChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.AiChatService",
	HandlerType: (*AiChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _AiChatService_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _AiChatService_UpdateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _AiChatService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AiChatService_ListSessions_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _AiChatService_DeleteSession_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _AiChatService_Record_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _AiChatService_UpdateRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _AiChatService_ListRecords_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _AiChatService_DeleteRecord_Handler,
		},
		{
			MethodName: "UploadAppendixs",
			Handler:    _AiChatService_UploadAppendixs_Handler,
		},
		{
			MethodName: "UpdateAppendix",
			Handler:    _AiChatService_UpdateAppendix_Handler,
		},
		{
			MethodName: "ListAppendixs",
			Handler:    _AiChatService_ListAppendixs_Handler,
		},
		{
			MethodName: "DeleteAppendix",
			Handler:    _AiChatService_DeleteAppendix_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _AiChatService_Generate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateModal",
			Handler:       _AiChatService_GenerateModal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
