// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // uuid string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSessionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyWords      string                 `protobuf:"bytes,4,opt,name=key_words,json=keyWords,proto3" json:"key_words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSessionsRequest) GetKeyWords() string {
	if x != nil {
		return x.KeyWords
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*GetSessionResponse  `protobuf:"bytes,1,rep,name=Sessions,proto3" json:"Sessions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*GetSessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessnoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessnoResponse) Reset() {
	*x = DeleteSessnoResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessnoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessnoResponse) ProtoMessage() {}

func (x *DeleteSessnoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessnoResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessnoResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AiModel       string                 `protobuf:"bytes,3,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 获取对应的: 历史消息, 附件信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *GenerateRequest) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *GenerateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// todo: stream response
type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

type GenerateModalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AiModel       string                 `protobuf:"bytes,3,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 获取对应的: 历史消息, 附件信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateModalRequest) Reset() {
	*x = GenerateModalRequest{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateModalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateModalRequest) ProtoMessage() {}

func (x *GenerateModalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateModalRequest.ProtoReflect.Descriptor instead.
func (*GenerateModalRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateModalRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateModalRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *GenerateModalRequest) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *GenerateModalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// todo: stream response
type GenerateModalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateModalResponse) Reset() {
	*x = GenerateModalResponse{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateModalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateModalResponse) ProtoMessage() {}

func (x *GenerateModalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateModalResponse.ProtoReflect.Descriptor instead.
func (*GenerateModalResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AiModel       string                 `protobuf:"bytes,3,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *RecordRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *RecordRequest) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int32                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RecordResponse) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int32                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	AiMessage     string                 `protobuf:"bytes,2,opt,name=ai_message,json=aiMessage,proto3" json:"ai_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRecordRequest) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *UpdateRecordRequest) GetAiMessage() string {
	if x != nil {
		return x.AiMessage
	}
	return ""
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	mi := &file_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{17}
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{18}
}

func (x *ListRecordsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int32                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AiMessage     string                 `protobuf:"bytes,3,opt,name=ai_message,json=aiMessage,proto3" json:"ai_message,omitempty"`
	AiModel       string                 `protobuf:"bytes,4,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{19}
}

func (x *Record) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *Record) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *Record) GetAiMessage() string {
	if x != nil {
		return x.AiMessage
	}
	return ""
}

func (x *Record) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *Record) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Record) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{20}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int32                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRecordRequest) GetRecordId() int32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{22}
}

type UploadAppendixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Source        int32                  `protobuf:"varint,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAppendixRequest) Reset() {
	*x = UploadAppendixRequest{}
	mi := &file_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAppendixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppendixRequest) ProtoMessage() {}

func (x *UploadAppendixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppendixRequest.ProtoReflect.Descriptor instead.
func (*UploadAppendixRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{23}
}

func (x *UploadAppendixRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UploadAppendixRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *UploadAppendixRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadAppendixRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UploadAppendixRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadAppendixRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

type UploadAppendixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppendixId    int32                  `protobuf:"varint,1,opt,name=appendix_id,json=appendixId,proto3" json:"appendix_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAppendixResponse) Reset() {
	*x = UploadAppendixResponse{}
	mi := &file_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAppendixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppendixResponse) ProtoMessage() {}

func (x *UploadAppendixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppendixResponse.ProtoReflect.Descriptor instead.
func (*UploadAppendixResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{24}
}

func (x *UploadAppendixResponse) GetAppendixId() int32 {
	if x != nil {
		return x.AppendixId
	}
	return 0
}

type UpdateAppendixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppendixId    int32                  `protobuf:"varint,1,opt,name=appendix_id,json=appendixId,proto3" json:"appendix_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppendixRequest) Reset() {
	*x = UpdateAppendixRequest{}
	mi := &file_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppendixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppendixRequest) ProtoMessage() {}

func (x *UpdateAppendixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppendixRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppendixRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateAppendixRequest) GetAppendixId() int32 {
	if x != nil {
		return x.AppendixId
	}
	return 0
}

func (x *UpdateAppendixRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type UpdateAppendixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppendixResponse) Reset() {
	*x = UpdateAppendixResponse{}
	mi := &file_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppendixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppendixResponse) ProtoMessage() {}

func (x *UpdateAppendixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppendixResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppendixResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{26}
}

type ListAppendixsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppendixsRequest) Reset() {
	*x = ListAppendixsRequest{}
	mi := &file_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppendixsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppendixsRequest) ProtoMessage() {}

func (x *ListAppendixsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppendixsRequest.ProtoReflect.Descriptor instead.
func (*ListAppendixsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{27}
}

func (x *ListAppendixsRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type Appendix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppendixId    int32                  `protobuf:"varint,1,opt,name=appendix_id,json=appendixId,proto3" json:"appendix_id,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Source        int32                  `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appendix) Reset() {
	*x = Appendix{}
	mi := &file_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appendix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appendix) ProtoMessage() {}

func (x *Appendix) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appendix.ProtoReflect.Descriptor instead.
func (*Appendix) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{28}
}

func (x *Appendix) GetAppendixId() int32 {
	if x != nil {
		return x.AppendixId
	}
	return 0
}

func (x *Appendix) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Appendix) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Appendix) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Appendix) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Appendix) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Appendix) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListAppendixsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appendixs     []*Appendix            `protobuf:"bytes,1,rep,name=appendixs,proto3" json:"appendixs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppendixsResponse) Reset() {
	*x = ListAppendixsResponse{}
	mi := &file_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppendixsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppendixsResponse) ProtoMessage() {}

func (x *ListAppendixsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppendixsResponse.ProtoReflect.Descriptor instead.
func (*ListAppendixsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{29}
}

func (x *ListAppendixsResponse) GetAppendixs() []*Appendix {
	if x != nil {
		return x.Appendixs
	}
	return nil
}

func (x *ListAppendixsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteAppendixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppendixId    int32                  `protobuf:"varint,1,opt,name=appendix_id,json=appendixId,proto3" json:"appendix_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppendixRequest) Reset() {
	*x = DeleteAppendixRequest{}
	mi := &file_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppendixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppendixRequest) ProtoMessage() {}

func (x *DeleteAppendixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppendixRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppendixRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteAppendixRequest) GetAppendixId() int32 {
	if x != nil {
		return x.AppendixId
	}
	return 0
}

type DeleteAppendixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppendixResponse) Reset() {
	*x = DeleteAppendixResponse{}
	mi := &file_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppendixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppendixResponse) ProtoMessage() {}

func (x *DeleteAppendixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppendixResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppendixResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{31}
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\"E\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"K\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x17\n" +
	"\x15UpdateSessionResponse\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x87\x01\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"|\n" +
	"\x13ListSessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tkey_words\x18\x04 \x01(\tR\bkeyWords\"b\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bSessions\x18\x01 \x03(\v2\x18.chat.GetSessionResponseR\bSessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"N\n" +
	"\x14DeleteSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x16\n" +
	"\x14DeleteSessnoResponse\"\x87\x01\n" +
	"\x0fGenerateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x12\x19\n" +
	"\bai_model\x18\x03 \x01(\tR\aaiModel\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x12\n" +
	"\x10GenerateResponse\"\x8c\x01\n" +
	"\x14GenerateModalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x12\x19\n" +
	"\bai_model\x18\x03 \x01(\tR\aaiModel\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x17\n" +
	"\x15GenerateModalResponse\"l\n" +
	"\rRecordRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x12\x19\n" +
	"\bai_model\x18\x03 \x01(\tR\aaiModel\"-\n" +
	"\x0eRecordResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x05R\brecordId\"Q\n" +
	"\x13UpdateRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x05R\brecordId\x12\x1d\n" +
	"\n" +
	"ai_message\x18\x02 \x01(\tR\taiMessage\"\x16\n" +
	"\x14UpdateRecordResponse\"d\n" +
	"\x12ListRecordsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xc0\x01\n" +
	"\x06Record\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x05R\brecordId\x12!\n" +
	"\fuser_message\x18\x02 \x01(\tR\vuserMessage\x12\x1d\n" +
	"\n" +
	"ai_message\x18\x03 \x01(\tR\taiMessage\x12\x19\n" +
	"\bai_model\x18\x04 \x01(\tR\aaiModel\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"S\n" +
	"\x13ListRecordsResponse\x12&\n" +
	"\arecords\x18\x01 \x03(\v2\f.chat.RecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"2\n" +
	"\x13DeleteRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x05R\brecordId\"\x16\n" +
	"\x14DeleteRecordResponse\"\x9e\x01\n" +
	"\x15UploadAppendixRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x16\n" +
	"\x06source\x18\x06 \x01(\x05R\x06source\"9\n" +
	"\x16UploadAppendixResponse\x12\x1f\n" +
	"\vappendix_id\x18\x01 \x01(\x05R\n" +
	"appendixId\"L\n" +
	"\x15UpdateAppendixRequest\x12\x1f\n" +
	"\vappendix_id\x18\x01 \x01(\x05R\n" +
	"appendixId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"\x18\n" +
	"\x16UpdateAppendixResponse\"5\n" +
	"\x14ListAppendixsRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\"\xbd\x01\n" +
	"\bAppendix\x12\x1f\n" +
	"\vappendix_id\x18\x01 \x01(\x05R\n" +
	"appendixId\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06source\x18\x05 \x01(\x05R\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"[\n" +
	"\x15ListAppendixsResponse\x12,\n" +
	"\tappendixs\x18\x01 \x03(\v2\x0e.chat.AppendixR\tappendixs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"8\n" +
	"\x15DeleteAppendixRequest\x12\x1f\n" +
	"\vappendix_id\x18\x01 \x01(\x05R\n" +
	"appendixId\"\x18\n" +
	"\x16DeleteAppendixResponse2\xb6\b\n" +
	"\rAiChatService\x12H\n" +
	"\rCreateSession\x12\x1a.chat.CreateSessionRequest\x1a\x1b.chat.CreateSessionResponse\x12H\n" +
	"\rUpdateSession\x12\x1a.chat.UpdateSessionRequest\x1a\x1b.chat.UpdateSessionResponse\x12?\n" +
	"\n" +
	"GetSession\x12\x17.chat.GetSessionRequest\x1a\x18.chat.GetSessionResponse\x12E\n" +
	"\fListSessions\x12\x19.chat.ListSessionsRequest\x1a\x1a.chat.ListSessionsResponse\x12G\n" +
	"\rDeleteSession\x12\x1a.chat.DeleteSessionRequest\x1a\x1a.chat.DeleteSessnoResponse\x12;\n" +
	"\bGenerate\x12\x15.chat.GenerateRequest\x1a\x16.chat.GenerateResponse0\x01\x12J\n" +
	"\rGenerateModal\x12\x1a.chat.GenerateModalRequest\x1a\x1b.chat.GenerateModalResponse0\x01\x123\n" +
	"\x06Record\x12\x13.chat.RecordRequest\x1a\x14.chat.RecordResponse\x12E\n" +
	"\fUpdateRecord\x12\x19.chat.UpdateRecordRequest\x1a\x1a.chat.UpdateRecordResponse\x12B\n" +
	"\vListRecords\x12\x18.chat.ListRecordsRequest\x1a\x19.chat.ListRecordsResponse\x12E\n" +
	"\fDeleteRecord\x12\x19.chat.DeleteRecordRequest\x1a\x1a.chat.DeleteRecordResponse\x12L\n" +
	"\x0fUploadAppendixs\x12\x1b.chat.UploadAppendixRequest\x1a\x1c.chat.UploadAppendixResponse\x12K\n" +
	"\x0eUpdateAppendix\x12\x1b.chat.UpdateAppendixRequest\x1a\x1c.chat.UpdateAppendixResponse\x12H\n" +
	"\rListAppendixs\x12\x1a.chat.ListAppendixsRequest\x1a\x1b.chat.ListAppendixsResponse\x12K\n" +
	"\x0eDeleteAppendix\x12\x1b.chat.DeleteAppendixRequest\x1a\x1c.chat.DeleteAppendixResponseB&Z$example.com/nano_template/proto/chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_chat_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: chat.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: chat.CreateSessionResponse
	(*UpdateSessionRequest)(nil),   // 2: chat.UpdateSessionRequest
	(*UpdateSessionResponse)(nil),  // 3: chat.UpdateSessionResponse
	(*GetSessionRequest)(nil),      // 4: chat.GetSessionRequest
	(*GetSessionResponse)(nil),     // 5: chat.GetSessionResponse
	(*ListSessionsRequest)(nil),    // 6: chat.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 7: chat.ListSessionsResponse
	(*DeleteSessionRequest)(nil),   // 8: chat.DeleteSessionRequest
	(*DeleteSessnoResponse)(nil),   // 9: chat.DeleteSessnoResponse
	(*GenerateRequest)(nil),        // 10: chat.GenerateRequest
	(*GenerateResponse)(nil),       // 11: chat.GenerateResponse
	(*GenerateModalRequest)(nil),   // 12: chat.GenerateModalRequest
	(*GenerateModalResponse)(nil),  // 13: chat.GenerateModalResponse
	(*RecordRequest)(nil),          // 14: chat.RecordRequest
	(*RecordResponse)(nil),         // 15: chat.RecordResponse
	(*UpdateRecordRequest)(nil),    // 16: chat.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),   // 17: chat.UpdateRecordResponse
	(*ListRecordsRequest)(nil),     // 18: chat.ListRecordsRequest
	(*Record)(nil),                 // 19: chat.Record
	(*ListRecordsResponse)(nil),    // 20: chat.ListRecordsResponse
	(*DeleteRecordRequest)(nil),    // 21: chat.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),   // 22: chat.DeleteRecordResponse
	(*UploadAppendixRequest)(nil),  // 23: chat.UploadAppendixRequest
	(*UploadAppendixResponse)(nil), // 24: chat.UploadAppendixResponse
	(*UpdateAppendixRequest)(nil),  // 25: chat.UpdateAppendixRequest
	(*UpdateAppendixResponse)(nil), // 26: chat.UpdateAppendixResponse
	(*ListAppendixsRequest)(nil),   // 27: chat.ListAppendixsRequest
	(*Appendix)(nil),               // 28: chat.Appendix
	(*ListAppendixsResponse)(nil),  // 29: chat.ListAppendixsResponse
	(*DeleteAppendixRequest)(nil),  // 30: chat.DeleteAppendixRequest
	(*DeleteAppendixResponse)(nil), // 31: chat.DeleteAppendixResponse
}
var file_chat_proto_depIdxs = []int32{
	5,  // 0: chat.ListSessionsResponse.Sessions:type_name -> chat.GetSessionResponse
	19, // 1: chat.ListRecordsResponse.records:type_name -> chat.Record
	28, // 2: chat.ListAppendixsResponse.appendixs:type_name -> chat.Appendix
	0,  // 3: chat.AiChatService.CreateSession:input_type -> chat.CreateSessionRequest
	2,  // 4: chat.AiChatService.UpdateSession:input_type -> chat.UpdateSessionRequest
	4,  // 5: chat.AiChatService.GetSession:input_type -> chat.GetSessionRequest
	6,  // 6: chat.AiChatService.ListSessions:input_type -> chat.ListSessionsRequest
	8,  // 7: chat.AiChatService.DeleteSession:input_type -> chat.DeleteSessionRequest
	10, // 8: chat.AiChatService.Generate:input_type -> chat.GenerateRequest
	12, // 9: chat.AiChatService.GenerateModal:input_type -> chat.GenerateModalRequest
	14, // 10: chat.AiChatService.Record:input_type -> chat.RecordRequest
	16, // 11: chat.AiChatService.UpdateRecord:input_type -> chat.UpdateRecordRequest
	18, // 12: chat.AiChatService.ListRecords:input_type -> chat.ListRecordsRequest
	21, // 13: chat.AiChatService.DeleteRecord:input_type -> chat.DeleteRecordRequest
	23, // 14: chat.AiChatService.UploadAppendixs:input_type -> chat.UploadAppendixRequest
	25, // 15: chat.AiChatService.UpdateAppendix:input_type -> chat.UpdateAppendixRequest
	27, // 16: chat.AiChatService.ListAppendixs:input_type -> chat.ListAppendixsRequest
	30, // 17: chat.AiChatService.DeleteAppendix:input_type -> chat.DeleteAppendixRequest
	1,  // 18: chat.AiChatService.CreateSession:output_type -> chat.CreateSessionResponse
	3,  // 19: chat.AiChatService.UpdateSession:output_type -> chat.UpdateSessionResponse
	5,  // 20: chat.AiChatService.GetSession:output_type -> chat.GetSessionResponse
	7,  // 21: chat.AiChatService.ListSessions:output_type -> chat.ListSessionsResponse
	9,  // 22: chat.AiChatService.DeleteSession:output_type -> chat.DeleteSessnoResponse
	11, // 23: chat.AiChatService.Generate:output_type -> chat.GenerateResponse
	13, // 24: chat.AiChatService.GenerateModal:output_type -> chat.GenerateModalResponse
	15, // 25: chat.AiChatService.Record:output_type -> chat.RecordResponse
	17, // 26: chat.AiChatService.UpdateRecord:output_type -> chat.UpdateRecordResponse
	20, // 27: chat.AiChatService.ListRecords:output_type -> chat.ListRecordsResponse
	22, // 28: chat.AiChatService.DeleteRecord:output_type -> chat.DeleteRecordResponse
	24, // 29: chat.AiChatService.UploadAppendixs:output_type -> chat.UploadAppendixResponse
	26, // 30: chat.AiChatService.UpdateAppendix:output_type -> chat.UpdateAppendixResponse
	29, // 31: chat.AiChatService.ListAppendixs:output_type -> chat.ListAppendixsResponse
	31, // 32: chat.AiChatService.DeleteAppendix:output_type -> chat.DeleteAppendixResponse
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
