basePath: /api/v1
definitions:
  example_com_nano_template_pkg_config.TemplateFrontMatter:
    properties:
      role:
        type: string
    type: object
  example_com_nano_template_pkg_middleware.EmptyData:
    type: object
  example_com_nano_template_pkg_middleware.Response:
    properties:
      code:
        description: 0 for success, 1 for failure, -1 for error
        type: integer
      data:
        description: response data
      message:
        description: response message
        type: string
    type: object
  pkg_services_common.InspectResponse:
    properties:
      author:
        type: string
      description:
        type: string
      version:
        type: string
    type: object
  pkg_services_common.TemplateResponse:
    properties:
      content:
        type: string
      frontmatter:
        $ref: '#/definitions/example_com_nano_template_pkg_config.TemplateFrontMatter'
      id:
        type: string
    type: object
  pkg_services_native_aliyun.PresignRequest:
    properties:
      mime:
        type: string
      object_key:
        type: string
      sender:
        description: 发送方, 作为标识字段, 无特殊含义
        type: string
      size:
        type: integer
    type: object
  pkg_services_native_aliyun.PresignResponse:
    properties:
      expiration:
        type: string
      method:
        type: string
      signed_headers:
        items:
          $ref: '#/definitions/pkg_services_native_aliyun.SignedHeader'
        type: array
      signed_url:
        type: string
    type: object
  pkg_services_native_aliyun.SignedHeader:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  pkg_services_user_sys.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  pkg_services_user_sys.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  pkg_services_user_sys.LoginResponse:
    properties:
      token:
        type: string
    type: object
  pkg_services_user_sys.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  pkg_services_user_sys.RegisterResponse:
    properties:
      user_id:
        type: integer
    type: object
  pkg_services_user_sys.UpdateUserProfileRequest:
    properties:
      avatar:
        type: string
      email:
        type: string
      gender:
        type: string
      nickname:
        type: string
      signature:
        type: string
    type: object
  pkg_services_user_sys.UserWithProfile:
    properties:
      avatar:
        type: string
      email:
        type: string
      gender:
        type: string
      nickname:
        type: string
      signature:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: swagger for nano template
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nano Template Api
  version: "1.0"
paths:
  /inspect:
    get:
      consumes:
      - application/json
      description: inspect server information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_common.InspectResponse'
              type: object
      summary: inspect server information
      tags:
      - example
  /native/aliyun/presign:
    post:
      consumes:
      - application/json
      description: presign aliyun oss object
      parameters:
      - description: presign request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/pkg_services_native_aliyun.PresignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_native_aliyun.PresignResponse'
              type: object
      summary: presign aliyun oss object
      tags:
      - aliyun
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: ping health check
      tags:
      - example
  /template/{template_id}:
    get:
      consumes:
      - application/json
      description: get template by id
      parameters:
      - description: Template ID
        in: path
        name: template_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_common.TemplateResponse'
              type: object
      summary: get template by id
      tags:
      - example
  /user/delete:
    delete:
      consumes:
      - application/json
      description: deactivate current authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/example_com_nano_template_pkg_middleware.EmptyData'
              type: object
      summary: deactivate user
      tags:
      - user
  /user/details:
    get:
      consumes:
      - application/json
      description: get current authenticated user details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_user_sys.UserWithProfile'
              type: object
      summary: get user details
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: authenticate user and return jwt token
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg_services_user_sys.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_user_sys.LoginResponse'
              type: object
      summary: login user
      tags:
      - user
  /user/logout:
    get:
      consumes:
      - application/json
      description: user logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/example_com_nano_template_pkg_middleware.EmptyData'
              type: object
      summary: logout user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: register a new user account
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg_services_user_sys.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/pkg_services_user_sys.RegisterResponse'
              type: object
      summary: register user
      tags:
      - user
  /user/update/password:
    put:
      consumes:
      - application/json
      description: change password for current authenticated user
      parameters:
      - description: Change password request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg_services_user_sys.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/example_com_nano_template_pkg_middleware.EmptyData'
              type: object
      summary: change user password
      tags:
      - user
  /user/update/profile:
    put:
      consumes:
      - application/json
      description: update profile fields for current authenticated user
      parameters:
      - description: Update user profile request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg_services_user_sys.UpdateUserProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/example_com_nano_template_pkg_middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/example_com_nano_template_pkg_middleware.EmptyData'
              type: object
      summary: update user profile
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: jwt format： Bearer {token}
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
